version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_saas
    depends_on:
      - mysql_saas

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_saas
    depends_on:
      - app

  mysql_saas:
    image: mysql:8.0
    container_name: mysql_saas
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_saas
      MYSQL_ROOT_PASSWORD: laravel_saas
      MYSQL_USER: laravel_saas
      MYSQL_PASSWORD: laravel_saas
    ports:
      - "3309:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_saas

volumes:
  dbdata:

networks:
  laravel_saas:
    driver: bridge 